//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 9 storyboards.
  struct storyboard {
    /// Storyboard `AddChosenPhoto`.
    static let addChosenPhoto = _R.storyboard.addChosenPhoto()
    /// Storyboard `CustomActivityIndicatorStoryBoard`.
    static let customActivityIndicatorStoryBoard = _R.storyboard.customActivityIndicatorStoryBoard()
    /// Storyboard `FullImageInfo`.
    static let fullImageInfo = _R.storyboard.fullImageInfo()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `MainGallery`.
    static let mainGallery = _R.storyboard.mainGallery()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `ProfileSettings`.
    static let profileSettings = _R.storyboard.profileSettings()
    /// Storyboard `SignIn`.
    static let signIn = _R.storyboard.signIn()
    /// Storyboard `SignUp`.
    static let signUp = _R.storyboard.signUp()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "AddChosenPhoto", bundle: ...)`
    static func addChosenPhoto(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.addChosenPhoto)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "CustomActivityIndicatorStoryBoard", bundle: ...)`
    static func customActivityIndicatorStoryBoard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.customActivityIndicatorStoryBoard)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "FullImageInfo", bundle: ...)`
    static func fullImageInfo(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.fullImageInfo)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "MainGallery", bundle: ...)`
    static func mainGallery(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.mainGallery)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "ProfileSettings", bundle: ...)`
    static func profileSettings(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.profileSettings)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "SignIn", bundle: ...)`
    static func signIn(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.signIn)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "SignUp", bundle: ...)`
    static func signUp(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.signUp)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.image` struct is generated, and contains static references to 16 images.
  struct image {
    /// Image `CustomLoadActivityIndicator`.
    static let customLoadActivityIndicator = Rswift.ImageResource(bundle: R.hostingBundle, name: "CustomLoadActivityIndicator")
    /// Image `EnrtySignInLogo`.
    static let enrtySignInLogo = Rswift.ImageResource(bundle: R.hostingBundle, name: "EnrtySignInLogo")
    /// Image `EntryFirstScreenLogo`.
    static let entryFirstScreenLogo = Rswift.ImageResource(bundle: R.hostingBundle, name: "EntryFirstScreenLogo")
    /// Image `EntryFirstScreenSignInButton`.
    static let entryFirstScreenSignInButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "EntryFirstScreenSignInButton")
    /// Image `EntryFirstScreenSignUpButton`.
    static let entryFirstScreenSignUpButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "EntryFirstScreenSignUpButton")
    /// Image `EntrySignInSignInButton`.
    static let entrySignInSignInButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "EntrySignInSignInButton")
    /// Image `EntrySignInSignUpButton`.
    static let entrySignInSignUpButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "EntrySignInSignUpButton")
    /// Image `EntrySignUpLogo`.
    static let entrySignUpLogo = Rswift.ImageResource(bundle: R.hostingBundle, name: "EntrySignUpLogo")
    /// Image `EntrySignUpSignUpButton`.
    static let entrySignUpSignUpButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "EntrySignUpSignUpButton")
    /// Image `EntrySignUpSingInButton`.
    static let entrySignUpSingInButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "EntrySignUpSingInButton")
    /// Image `LoadingImage`.
    static let loadingImage = Rswift.ImageResource(bundle: R.hostingBundle, name: "LoadingImage")
    /// Image `Logo`.
    static let logo = Rswift.ImageResource(bundle: R.hostingBundle, name: "Logo")
    /// Image `ProfileSettingsButton`.
    static let profileSettingsButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "ProfileSettingsButton")
    /// Image `ProfileUserPhoto`.
    static let profileUserPhoto = Rswift.ImageResource(bundle: R.hostingBundle, name: "ProfileUserPhoto")
    /// Image `Welcome!`.
    static let welcome = Rswift.ImageResource(bundle: R.hostingBundle, name: "Welcome!")
    /// Image `profileLine`.
    static let profileLine = Rswift.ImageResource(bundle: R.hostingBundle, name: "profileLine")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "CustomLoadActivityIndicator", bundle: ..., traitCollection: ...)`
    static func customLoadActivityIndicator(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.customLoadActivityIndicator, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "EnrtySignInLogo", bundle: ..., traitCollection: ...)`
    static func enrtySignInLogo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.enrtySignInLogo, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "EntryFirstScreenLogo", bundle: ..., traitCollection: ...)`
    static func entryFirstScreenLogo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.entryFirstScreenLogo, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "EntryFirstScreenSignInButton", bundle: ..., traitCollection: ...)`
    static func entryFirstScreenSignInButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.entryFirstScreenSignInButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "EntryFirstScreenSignUpButton", bundle: ..., traitCollection: ...)`
    static func entryFirstScreenSignUpButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.entryFirstScreenSignUpButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "EntrySignInSignInButton", bundle: ..., traitCollection: ...)`
    static func entrySignInSignInButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.entrySignInSignInButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "EntrySignInSignUpButton", bundle: ..., traitCollection: ...)`
    static func entrySignInSignUpButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.entrySignInSignUpButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "EntrySignUpLogo", bundle: ..., traitCollection: ...)`
    static func entrySignUpLogo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.entrySignUpLogo, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "EntrySignUpSignUpButton", bundle: ..., traitCollection: ...)`
    static func entrySignUpSignUpButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.entrySignUpSignUpButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "EntrySignUpSingInButton", bundle: ..., traitCollection: ...)`
    static func entrySignUpSingInButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.entrySignUpSingInButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "LoadingImage", bundle: ..., traitCollection: ...)`
    static func loadingImage(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.loadingImage, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Logo", bundle: ..., traitCollection: ...)`
    static func logo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.logo, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ProfileSettingsButton", bundle: ..., traitCollection: ...)`
    static func profileSettingsButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.profileSettingsButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ProfileUserPhoto", bundle: ..., traitCollection: ...)`
    static func profileUserPhoto(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.profileUserPhoto, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Welcome!", bundle: ..., traitCollection: ...)`
    static func welcome(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.welcome, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "profileLine", bundle: ..., traitCollection: ...)`
    static func profileLine(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.profileLine, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"
            static let uiSceneStoryboardFile = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneStoryboardFile") ?? "Main"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    /// Nib `MainGalleryCollectionViewCell`.
    static let mainGalleryCollectionViewCell = _R.nib._MainGalleryCollectionViewCell()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "MainGalleryCollectionViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.mainGalleryCollectionViewCell) instead")
    static func mainGalleryCollectionViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.mainGalleryCollectionViewCell)
    }
    #endif

    static func mainGalleryCollectionViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> MainGalleryCollectionViewCell? {
      return R.nib.mainGalleryCollectionViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MainGalleryCollectionViewCell
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib {
    struct _MainGalleryCollectionViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "MainGalleryCollectionViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> MainGalleryCollectionViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MainGalleryCollectionViewCell
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try addChosenPhoto.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try customActivityIndicatorStoryBoard.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try fullImageInfo.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try main.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try mainGallery.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try profileSettings.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try signIn.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try signUp.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct addChosenPhoto: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "AddChosenPhoto"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct customActivityIndicatorStoryBoard: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "CustomActivityIndicatorStoryBoard"

      static func validate() throws {
        if UIKit.UIImage(named: "CustomLoadActivityIndicator", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'CustomLoadActivityIndicator' is used in storyboard 'CustomActivityIndicatorStoryBoard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "LoadingImage", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'LoadingImage' is used in storyboard 'CustomActivityIndicatorStoryBoard', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct fullImageInfo: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let fullImageInfo = StoryboardViewControllerResource<FullImageInfoViewController>(identifier: "FullImageInfo")
      let name = "FullImageInfo"

      func fullImageInfo(_: Void = ()) -> FullImageInfoViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: fullImageInfo)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.fullImageInfo().fullImageInfo() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'fullImageInfo' could not be loaded from storyboard 'FullImageInfo' as 'FullImageInfoViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if UIKit.UIImage(named: "EntryFirstScreenLogo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'EntryFirstScreenLogo' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController

      let bundle = R.hostingBundle
      let entryNavigationController = StoryboardViewControllerResource<UIKit.UINavigationController>(identifier: "EntryNavigationController")
      let name = "Main"
      let startViewController = StoryboardViewControllerResource<StartViewController>(identifier: "StartViewController")

      func entryNavigationController(_: Void = ()) -> UIKit.UINavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: entryNavigationController)
      }

      func startViewController(_: Void = ()) -> StartViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: startViewController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "EntryFirstScreenLogo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'EntryFirstScreenLogo' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "EntryFirstScreenSignInButton", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'EntryFirstScreenSignInButton' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "EntryFirstScreenSignUpButton", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'EntryFirstScreenSignUpButton' is used in storyboard 'Main', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.main().entryNavigationController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'entryNavigationController' could not be loaded from storyboard 'Main' as 'UIKit.UINavigationController'.") }
        if _R.storyboard.main().startViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'startViewController' could not be loaded from storyboard 'Main' as 'StartViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct mainGallery: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UITabBarController

      let bundle = R.hostingBundle
      let mainGalleryTabBarController = StoryboardViewControllerResource<UIKit.UITabBarController>(identifier: "MainGalleryTabBarController")
      let name = "MainGallery"

      func mainGalleryTabBarController(_: Void = ()) -> UIKit.UITabBarController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: mainGalleryTabBarController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "CustomLoadActivityIndicator", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'CustomLoadActivityIndicator' is used in storyboard 'MainGallery', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ProfileSettingsButton", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'ProfileSettingsButton' is used in storyboard 'MainGallery', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ProfileUserPhoto", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'ProfileUserPhoto' is used in storyboard 'MainGallery', but couldn't be loaded.") }
        if UIKit.UIImage(named: "profileLine", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'profileLine' is used in storyboard 'MainGallery', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.mainGallery().mainGalleryTabBarController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'mainGalleryTabBarController' could not be loaded from storyboard 'MainGallery' as 'UIKit.UITabBarController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct profileSettings: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "ProfileSettings"
      let profileSettings = StoryboardViewControllerResource<ProfileSettingsViewController>(identifier: "ProfileSettings")

      func profileSettings(_: Void = ()) -> ProfileSettingsViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: profileSettings)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "ProfileUserPhoto", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'ProfileUserPhoto' is used in storyboard 'ProfileSettings', but couldn't be loaded.") }
        if UIKit.UIImage(named: "profileLine", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'profileLine' is used in storyboard 'ProfileSettings', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.profileSettings().profileSettings() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'profileSettings' could not be loaded from storyboard 'ProfileSettings' as 'ProfileSettingsViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct signIn: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "SignIn"
      let signInViewController = StoryboardViewControllerResource<SignInViewController>(identifier: "SignInViewController")

      func signInViewController(_: Void = ()) -> SignInViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: signInViewController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "CustomLoadActivityIndicator", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'CustomLoadActivityIndicator' is used in storyboard 'SignIn', but couldn't be loaded.") }
        if UIKit.UIImage(named: "EnrtySignInLogo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'EnrtySignInLogo' is used in storyboard 'SignIn', but couldn't be loaded.") }
        if UIKit.UIImage(named: "EntrySignInSignInButton", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'EntrySignInSignInButton' is used in storyboard 'SignIn', but couldn't be loaded.") }
        if UIKit.UIImage(named: "EntrySignInSignUpButton", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'EntrySignInSignUpButton' is used in storyboard 'SignIn', but couldn't be loaded.") }
        if UIKit.UIImage(named: "LoadingImage", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'LoadingImage' is used in storyboard 'SignIn', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.signIn().signInViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'signInViewController' could not be loaded from storyboard 'SignIn' as 'SignInViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct signUp: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "SignUp"
      let signUpViewController = StoryboardViewControllerResource<SignUpViewController>(identifier: "SignUpViewController")

      func signUpViewController(_: Void = ()) -> SignUpViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: signUpViewController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "EntrySignUpLogo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'EntrySignUpLogo' is used in storyboard 'SignUp', but couldn't be loaded.") }
        if UIKit.UIImage(named: "EntrySignUpSignUpButton", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'EntrySignUpSignUpButton' is used in storyboard 'SignUp', but couldn't be loaded.") }
        if UIKit.UIImage(named: "EntrySignUpSingInButton", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'EntrySignUpSingInButton' is used in storyboard 'SignUp', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.signUp().signUpViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'signUpViewController' could not be loaded from storyboard 'SignUp' as 'SignUpViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
